# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    #secrets:
      # Required if you plan to publish (uncomment the below)
      # moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      codechecker_max_warnings: 0 # CI should now fail on phpcs / code checker warnings.
      disable_behat: true
      disable_grunt: true
      min_php: 8.1
      extra_plugin_runners: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y graphviz;
          sudo fc-cache
